### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by interstella-5555**
synced with latest https://github.com/SkynetLabs/ansiblecm/pull/6 and resolved conflicts

### CODE REVIEW

**Review by MSevey — APPROVED** [review]

**Comment by interstella-5555** [comment]
I'm going to try and test it tomorrow

**Comment by firyx** [comment]
Upgrading Ansible (from upstream) can break our playbooks.
Why?
- Ansible changes hidden, implicit default values in upgraded modules and our playbooks are thoroughly tested with the specific behavior of the current versions of the modules. If we upgrade, some things can break and we might even not know about these (some of our flags/conditions might not be set correctly => some code might not be executed or will be executed unintentionatelly, e.g. cluster config can be unintentionatelly regenerated with newly generated values etc.).

**Review by firyx — CHANGES_REQUESTED** [review]
See my comment above.

**Comment by interstella-5555** [comment]
@firyx so what are you suggesting? Doesn't it mean we should test the playbooks and see if they work and adjust if needed or you're saying we should not consider upgrading at all ?

**Comment by interstella-5555** [comment]
not on the current roadmap

**Pull request closed without merging**
